#!/bin/bash

function install_gh() {
    echo "Installing gh..."

    # architecture
    local arch=$(uname -m)

    case "$OSTYPE" in
        darwin*)  os="macOS";;
        msys*)    os="windows";;
        *)        
            echo "Currently only support macOS and Windows"
            exit
            ;;
    esac

    case $arch in
        x86_64) arch="amd64";;
        aarch64) arch="arm64";;
        *)  
            echo "Unsupported architecture: $arch"
            exit
        ;;
    esac

    # download latest gh
    curl -s https://api.github.com/repos/cli/cli/releases/latest \
        | grep "browser_download_url.*gh_" \
        | cut -d: -f 2,3 \
        | tr -d \" | tr -d ' '  \
        | grep $os \
        | grep $arch \
        | xargs -I {} curl -O -L {}

    # unzip zip file
    unzip gh_*_$os_$arch.zip

    # move gh to /usr/local/bin
    mv gh_*_$os_$arch/bin/gh /usr/local/bin

    # remove downloaded files
    rm -rf gh_*_$os_$arch.zip gh_*_$os_$arch

    echo -e "\e[1;32mgh installed successfully\e[0m"
}